### PR TITLE
Change histogram from amplitude bins to frequency bins

### PR DESCRIPTION
**Pull request by fcr**
The original code was producing histograms where the bins are ranges of amplitudes. This does not really reflect what is happening in music.
This pull request has changed this so that the bins now contain frequency ranges.
With this change the anomaly detector works well even with the default values out of the box.
Using it with jazz, it detects where the main theme is repeated (no anomalies) and where there is improvisation (anomalies).
Unfortunately this makes the code inconsistent with the video.
Other changes are that stereo recordings are accepted and it runs on a Mac with El Capitan.
I've attached a sample from the end of Esperanza Spalding's "The Peacocks". where they end on the repeated main theme. Her bass playing is easy to identify
peacocks_5hz_10b
.

### CODE REVIEW

**Comment by rhyolight** [comment]
@fcr This is amazing! Thank you! I want to merge this, but first I think I need to find the time to give it a good review and test it out with some more wav files. I'm so glad you got it working and found ways to improve it!

I'm neck-deep in moving Nupic to a new CI system right now, so please give me some time to review. I'll get back to it as soon as I can. Thanks again!

**Comment by rcrowder** [comment]
Yes. I reviewed this earlier and almost replied. Very nice update Fred! This looks good to merge, pending a review and test from @rhyolight ?

**Comment by rhyolight** [comment]
@rcrowder Yes I want to test it out first with my original audio files to see how it improved. But the code looks sound to me. I knew I had a fundamental mistake in my audio processing, I even asked around the office for people to help me find it.

**Comment by rhyolight** [comment]
btw @rcrowder if you are interested in testing this, let me know. If you say it works, I'll merge it. I just don't have much time right now.

**Comment by fcr** [comment]
Hi , I added additional changes so that it runs with Nupic version 0.7

**Comment by rhyolight** [comment]
Thanks @fcr!

**Pull request merged**
